name: master

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: github/super-linter@v3
  test:
    runs-on: ubuntu-latest
    needs: 
      - build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        uses: github/super-linter@v3
      - run: npx nx affected --target=test --parallel=3