name: master

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: bahmutov/npm-install@v1
        with:
          path: ./node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - run: npm ci

  build:
    runs-on: ubuntu-latest
    needs: 
      - install
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: github/super-linter@v3
  test:
    runs-on: ubuntu-latest
    needs: 
      - install
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3