name: pull-request

on: 
  pull_request:
    branches:
      - main
    type: 
      - synchronize
      - ready-for-review
      - opened
      - reopened


jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "16.15.1"
      - uses: actions/cache@v2
        with:
          path: ./node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - run: npm i

  build:
    runs-on: ubuntu-latest
    needs: 
      - install
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "16.15.1"
      - uses: actions/cache@v2
        with:
          path: node_modules/.cache/nx
          key: nx-${{ runner.os }}-${{ github.sha }}
          restore-keys: nx-${{ runner.os }}
      - uses: actions/cache@v2
        with:
          path: ./node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - run: npx nx affected --target=build -- --base --parallel=3

  test:
    runs-on: ubuntu-latest
    needs: 
      - install
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: node_modules/.cache/nx
          key: nx-${{ runner.os }}-${{ github.sha }}
          restore-keys: nx-${{ runner.os }}
      - uses: actions/cache@v2
        with:
          path: ./node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - run: npx nx affected --target=lint -- --base --parallel=3
      - run: npx nx affected --target=test -- --base --parallel=3